spring.application.name=tripItinerary

# # MySQL Configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/tripplannerItinerary?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
# spring.datasource.username=root
# spring.datasource.password=saif786


server.port=${PORT:8080}

# MySQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# ============================================================
# HIKARI CONNECTION POOL
# ============================================================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=300000

spring.datasource.hikari.keepalive-time=120000

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google Client

google.client-id=${GOOGLE_CLIENT_ID}



# JWT Configuration

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}






spring.application.name=tripItinerary

server.port=${PORT:8080}

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google
google.client-id=${GOOGLE_CLIENT_ID}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}